name: Release

on:
  push:
    branches: 
      - release/*

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Writing .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
    - name: Use Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        always-auth: true
    - name: Install deps.
      run: npm install
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
    - name: Publish
      run: npm run publish:linux
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
  windows:
    needs: [linux]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Writing .npmrc
      run: |
        chcp
        chcp 932
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >>  %USERPROFILE%\.npmrc
    - name: Use Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        always-auth: true
    - name: Install deps.
      run: npm install
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
    - name: Publish
      run: npm run publish:win
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
  mac:
    needs: [windows]
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Writing .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
    - name: Use Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        always-auth: true
    - name: Install deps.
      run: npm install
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
    - name: Publish
      run: npm run publish:mac
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
