name: Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Writing .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install deps.
      run: npm install
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
