name: Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry: https://npm.pkg.github.com
        scope: "@inkohx"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install deps.
      run: npm install
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
