name: Test

on:
  push:
    branches-ignore:
    - "release/*"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@inkohx'
    - name: Install deps.
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: lint
      run: npm run lint
    - name: compile
      run: npm run compile:test
